#declare your desktop app
#original - nap_desktop_app(maxmanage "" NRC_NONE)
nap_desktop_app(maxmanage "" NRC_EMBEDDED)
# link nappgui's opengl abstraction module - needed to embed 3rd party workflow editor that runs on opengl
nap_link_opengl(maxmanage)

#-----
nap_target_c_standard(maxmanage 99)
nap_target_cxx_standard(maxmanage 14)
# Replace 'my_target' with your actual target name
#target_compile_features(maxmanage PRIVATE c_std_99)
# Optional: Force the compiler to fail if it doesn't support C11
#set_target_properties(maxmanage PROPERTIES C_STANDARD_REQUIRED ON)
# Optional: Disable compiler-specific extensions (like GNU extensions) to use strict ISO C
#set_target_properties(maxmanage PROPERTIES C_EXTENSIONS OFF)
#-----
add_compile_options(-fsanitize=address)
add_compile_options(-g)
add_link_options(-fsanitize=address)
add_library(libxml2.so SHARED IMPORTED)
add_library(libmbedtls.so SHARED IMPORTED)
add_library(libmbedcrypto.so SHARED IMPORTED)
add_library(libmbedx509.so SHARED IMPORTED)
add_library(libssl.so SHARED IMPORTED)
add_library(libssh2.so SHARED IMPORTED)
add_library(libcrypto.so SHARED IMPORTED)
add_library(libjson-c.so SHARED IMPORTED)
add_library(libAdsLib.a SHARED IMPORTED)
add_library(libwebkit2gtk-4.1.so SHARED IMPORTED)
add_library(libpcap.so SHARED IMPORTED)
add_library(libmodbus.so SHARED IMPORTED)
#add_library(libmongoose.a SHARED IMPORTED)
set_property(TARGET libxml2.so PROPERTY IMPORTED_LOCATION /usr/lib/x86_64-linux-gnu/libxml2.so)
set_property(TARGET libmbedtls.so PROPERTY IMPORTED_LOCATION /usr/lib/x86_64-linux-gnu/libmbedtls.so)
set_property(TARGET libmbedcrypto.so PROPERTY IMPORTED_LOCATION /usr/lib/x86_64-linux-gnu/libmbedcrypto.so)
set_property(TARGET libmbedx509.so PROPERTY IMPORTED_LOCATION /usr/lib/x86_64-linux-gnu/libmbedx509.so)
set_property(TARGET libssl.so PROPERTY IMPORTED_LOCATION /usr/lib/x86_64-linux-gnu/libssl.so)
set_property(TARGET libssh2.so PROPERTY IMPORTED_LOCATION /usr/lib/x86_64-linux-gnu/libssh2.so)
set_property(TARGET libcrypto.so PROPERTY IMPORTED_LOCATION /usr/lib/x86_64-linux-gnu/libcrypto.so)
set_property(TARGET libjson-c.so PROPERTY IMPORTED_LOCATION /usr/lib/x86_64-linux-gnu/libjson-c.so)
set_property(TARGET libAdsLib.a PROPERTY IMPORTED_LOCATION /usr/local/src/ADS/build/libAdsLib.a)
set_property(TARGET libwebkit2gtk-4.1.so PROPERTY IMPORTED_LOCATION /lib/x86_64-linux-gnu/libwebkit2gtk-4.1.so)
set_property(TARGET libpcap.so PROPERTY IMPORTED_LOCATION /lib/x86_64-linux-gnu/libpcap.so)
set_property(TARGET libmodbus.so PROPERTY IMPORTED_LOCATION /usr/local/lib/libmodbus.so)
#set_property(TARGET libmongoose.a PROPERTY IMPORTED_LOCATION /usr/local/src/mongoose-7.22/test/libmongoose.a)
include_directories(/usr/include/libxml2)
include_directories(/usr/include/mbedtls)
include_directories(/usr/include/json-c)
include_directories(/usr/local/src/ADS/AdsLib)
include_directories(/usr/include/gtk-3.0)
include_directories(/usr/include/gtk-4.0)
include_directories(/usr/include/glib-4.0)
include_directories(/usr/lib/x86_64-linux-gnu/glib-2.0/include/)
include_directories(/usr/lib/x86_64-linux-gnu/glib2.0/include)
include_directories(/usr/include/cairo)
include_directories(/usr/include/pango-1.0)
include_directories(/usr/include/harfbuzz)
include_directories(/usr/include/gdk-pixbuf-2.0)
include_directories(/usr/include/graphene-1.0)
include_directories(/usr/lib/x86_64-linux-gnu/graphene-1.0/include)
include_directories(/usr/include/atk-1.0)
include_directories(/usr/local/include/)
include_directories(/usr/include/glib-2.0/)
include_directories(/usr/include/webkitgtk-4.1/webkit/)
include_directories(/usr/include/webkitgtk-4.1/webkit2/)
include_directories(/usr/include/webkitgtk-4.1/webkitdom/)
include_directories(/usr/include/webkitgtk-4.1/JavaScriptCore/)
include_directories(/usr/include/webkitgtk-4.1/jsc/)
include_directories(/home/pi/nappgui_src/build/demo/guihello/resgen/)
include_directories(/usr/include/)
link_directories(/usr/lib/x86_64-linux-gnu/)
target_link_libraries(maxmanage libxml2.so)
target_link_libraries(maxmanage libmbedtls.so)
target_link_libraries(maxmanage libmbedcrypto.so)
target_link_libraries(maxmanage libmbedx509.so)
target_link_libraries(maxmanage libssl.so)
target_link_libraries(maxmanage libssh2.so)
target_link_libraries(maxmanage libcrypto.so)
target_link_libraries(maxmanage libjson-c.so)
target_link_libraries(maxmanage libAdsLib.a)
target_link_libraries(maxmanage libwebkit2gtk-4.1.so)
target_link_libraries(maxmanage libpcap.so)
target_link_libraries(maxmanage libmodbus.so)
#target_link_libraries(maxmanage libmongoose.a)

set(NAPPGUI_WEB_SUPPORT YES CACHE BOOL "" FORCE)
